# Questão 1

Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

a) Crie um array aleatório de 15 itens entre 0 e 100;

b) Qual o maior número do array?

c) Qual a sua posição?

d) Verifique quais números do array são maior que 10;

e) Salve em uma nova lista apenas os itens entre 10 e 30.

In [3]:
import numpy as np

def run():
    array = np.random.randint(0, 100, 15)

    print(f'Array: {array}')

    print(f'Maior numero: {array.max()}')

    print(f'Posicao do maior numero: {array.argmax()}')

    print(f'Numeros maiores que 10: {array[array > 10]}')

    new_array = array[(array > 10) & (array < 30)]

    print(f'Nova lista: {new_array}')

run()

Array: [90 45 28 16 83  9  9 20 57 91 32 17  3 80 79]
Maior numero: 91
Posicao do maior numero: 9
Numeros maiores que 10: [90 45 28 16 83 20 57 91 32 17 80 79]
Nova lista: [28 16 20 17]


# Questão 2

Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o np.linspace();

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().

In [7]:
import numpy as np

matrix_a = np.linspace(0, 100, 6).reshape((3,2))

matrix_b = np.random.randint(0, 100, 10).reshape((5,2))

array = np.array([1, 0, 0, 1]).reshape((2,2))

print("Matriz A")
print(matrix_a)

print("Matriz B")
print(matrix_b)

print("Array")
print(array)

print("Resultado da multiplicacao")
print(np.matmul(matrix_a, array))

Matriz A
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]
Matriz B
[[37 21]
 [88  7]
 [89 14]
 [80  0]
 [51 19]]
Array
[[1 0]
 [0 1]]
Resultado da multiplicacao
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]
